name: Hello World
on: 
  [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update System
        run: |
          sudo apt update -y && sudo apt upgrade -y
      - name: Print Message
        run: |
          echo 'Hello World!'
